
name: Run Tests on Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # Step 4: Install Make
      - name: Install Make
        run: sudo apt-get install make -y

      # Step 5: Run the Makefile to build, run, test, and tear down
      - name: Build, Run, Test, and Tear Down
        run: make full-test

  packages:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_TOKEN3}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build and push Docker imageDOCKER_TOKEN2
        run: docker-compose -f docker-compose.yml build

      - name: Push Docker image to GitHub Container Registry
        run: docker-compose -f docker-compose.yml push
